FROM jupyter/minimal-notebook:2022-05-03

USER root

RUN git clone --depth=1 --branch=feature/dev-site https://github.com/IMMM-SFA/msd_uncertainty_ebook.git msd_uncertainty_ebook
RUN cd msd_uncertainty_ebook && pip install .

# Now create a symlinked data folder inside the msdbook package that links to /home/demo/data folder
RUN mkdir -p /home/demo/data
RUN rm -rf /opt/conda/lib/python3.9/site-packages/msdbook/data
RUN ln -s /home/demo/data /opt/conda/lib/python3.9/site-packages/msdbook/data


