name: Test

on:
  push:
    branches: [ main, dev ]
  schedule:
    - cron: '0 8 * * 1'  # Runs every monday at 12am Pacific time

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    env:
      OS: ${{ matrix.os }}
      PYTHON: '3.9'

    steps:

      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@master
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Install pytest-mock
        run: |
          pip install pytest-mock

      - name: Test and generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml

      - uses: codecov/codecov-action@v4
        with:
          files: ./coverage.xml # optional
          name: codecov-umbrella # optional
          token: ${{ secrets.CODECOV_TOKEN }} # required


      - name: Notify on failure
        if: failure()  # This step will only run if any previous step fails
        run: |
          echo "Build or tests failed. Please check the logs."
          
      - name: Test and generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pip install pytest-mock  # Ensure pytest-mock is installed before testing
          pytest --cov=./ --cov-report=xml  # Run tests and generate a coverage report
