name: Build

on:
  push:
    branches: [ main, dev ]

jobs:
  build:
      runs-on: ${{ matrix.os }}

      strategy:
        matrix:
          os: [ubuntu-latest]

      env:
        OS: ${{ matrix.os }}
        PYTHON: '3.9'

      steps:

        - uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@master
          with:
            python-version: 3.9

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Test and generate coverage report
          run: |
            pip install pytest
            pip install pytest-cov
            pytest --cov=./ --cov-report=xml

        # - name: Upload coverage to Codecov
        #   uses: codecov/codecov-action@v1
        #   with:
        #     file: ./coverage.xml
        #     fail_ci_if_error: true
